### ISSUE TITLE
Implement single active consumer for rabbit

### ISSUE THREAD

**Issue by ternsip** [spring-cloud/spring-cloud-stream-binder-rabbit#275] opened 2019-11-25 12:08 UTC
Hi.
I've spotted that RabbitExchangeQueueProvisioner does not have argument for rabbit argument option
x-single-active-consumer
Please add support for that.
I want to pass this via application.yml props.

**Comment by garyrussell** [comment] 2019-12-02 14:18
This is a duplicate of #274 it will be resolved when Spring AMQP 2.2.2 is released later this week.

**Closed by garyrussell** 2019-12-02 14:18 UTC
