### ISSUE TITLE
Investigate the need for explicit import of boot's RabbitAutoConfiguration in RabbitServiceAutoConfiguration

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream-binder-rabbit#289] opened 2020-04-23 13:48 UTC
Basically because we have an explicit import of  `RabbitAutoConfiguration` in `RabbitServiceAutoConfiguration`
```
        /**
	 * Configuration to be used when the cloud profile is not set. Defer to Spring Boot
	 * auto-configuration.
	 */
	@Configuration
	@Profile("!cloud")
	@Import(RabbitAutoConfiguration.class)
	protected static class NoCloudProfile {

	}
```
. . . explicit exclusion such as `@SpringBootApplication(exclude = RabbitAutoConfiguration.class)` becomes meaningless.

@garyrussell for any relevant input you may have on this would be nice

**Comment by garyrussell** [comment] 2020-04-23 14:51
Interesting; I have no idea why that's there; seems unnecessary to me.

**Comment by sabbyanandan** [comment] 2021-06-29 15:09
Is this a duplicate of #187?

**Comment by garyrussell** [comment] 2021-07-02 19:08
Duplicates #187

**Closed by garyrussell** 2021-07-02 19:08 UTC
Labels: duplicate
